### PR TITLE
updated polkadot package version and add ethereum type defs for dusty

### PR DESCRIPTION
**Pull request by hoonsubin**
This PR adds:
- ethereum type definitions (manually typed. We may need to update this when Polkadot-js has an official ethereum type definition built-in)
- fixes some of the bugs that were addressed from this release https://github.com/polkadot-js/api/issues/2756
- moves the metadata source endpoint (this will make the chain listen to Dusty for new types)
- changed local package alias from `plasm-types` to `@plasm/types`
- changed README to reflect these changes

### CODE REVIEW

**Comment by hoonsubin** [comment]
@satellitex @akru We might want to update the types soon and resolve the following issue.

```
Unable to resolve type ClaimId, it will fail on construction
Unable to resolve type Lockdrop, it will fail on construction
Unable to resolve type TickerRate, it will fail on construction
Unable to resolve type ClaimVote, it will fail on construction
Unable to resolve type Claim, it will fail on construction
Unable to resolve type StakingParameters, it will fail on construction
Unable to resolve type Parameters, it will fail on construction
Unable to resolve type EraStakingPoints, it will fail on construction
Unable to resolve type OfferState, it will fail on construction
Unable to resolve type OfferOf, it will fail on construction
Unable to resolve type Decision, it will fail on construction
Unable to resolve type ChallengeGameOf, it will fail on construction
Unable to resolve type PredicateContractOf, it will fail on construction
Unable to resolve type PredicateHash, it will fail on construction
Unable to resolve type PrefabOvmModule, it will fail on construction
Unable to resolve type Property, it will fail on construction
Unable to resolve type PropertyOf, it will fail on construction
Unable to resolve type Range, it will fail on construction
Unable to resolve type RangeOf, it will fail on construction
Unable to resolve type StateUpdate, it will fail on construction
Unable to resolve type Checkpoint, it will fail on construction
Unable to resolve type Exit, it will fail on construction
Unable to resolve type InclusionProof, it will fail on construction
Unable to resolve type IntervalInclusionProof, it will fail on construction
Unable to resolve type AddressInclusionProof, it will fail on construction
Unable to resolve type IntervalTreeNode, it will fail on construction
Unable to resolve type AddressTreeNode, it will fail on construction
Unable to resolve type ExitDeposit, it will fail on construction
```

**Review by satellitex — COMMENTED** [review]
For some types, some types do not exist in the Substrate EVM pallet. `Transaction`` TransactionStatus` etc.
Where did these get from?
https://github.com/paritytech/substrate/blob/v2.0.0/frame/evm/src/lib.rs

**Comment by hoonsubin** [comment]
@satellitex I got it from here: https://github.com/staketechnologies/frontier/blob/cc1040c13f7e78aef94b8a5c4fcf0d1b05db0cd5/rpc/primitives/src/lib.rs#L28
and `Transaction` from here https://github.com/staketechnologies/frontier/blob/aa3f001a55551060cfd95bf9116e958b0822cf3e/template/README.md#L60

The type gen script was showing an error if I don't add these...

**Review by satellitex — APPROVED** [review]
I understand. LGTM.

**Pull request merged**
